;; Metamod plugins.ini
; AMX Mod X 1.8.2

win32   addons\amxmodx\dlls\amxmodx_mm.dll
; Enable this instead for binary logging
 win32   addons\amxmodx\dlls\amxmodx_bl_mm.dll
win32 addons\reapi\reapi_amxx.dll
win32 addons\reunion\reunion_mm.dll

win32 addons/podbot/podbot_mm.dll